In [23]:
import hubspot_api.requests as hs
apikey="pat-eu1-91242dbb-e9d6-4b77-852f-fdd31151e049"#"pat-eu1-26e9ca6f-6614-4320-b7eb-15b6ec1d25fe" cpt test

In [22]:
myrep = hs.getBacklList(apikey)

In [10]:
import hubspot
from pprint import pprint
from hubspot.crm.companies import ApiException

client = hubspot.Client.create(access_token=apikey)

try:
    api_response = client.crm.companies.basic_api.get_page(limit=20, archived=False)
    pprint(api_response)
except ApiException as e:
    print("Exception when calling basic_api->get_page: %s\n" % e)

{'paging': {'next': {'after': '5961206774',
                     'link': 'https://api.hubapi.com/crm/v3/objects/companies?limit=20&archived=False&after=5961206774'}},
 'results': [{'archived': False,
              'archived_at': None,
              'associations': None,
              'created_at': datetime.datetime(2022, 8, 1, 12, 8, 19, 863000, tzinfo=tzutc()),
              'id': '5961164748',
              'properties': {'createdate': '2022-08-01T12:08:19.863Z',
                             'domain': None,
                             'hs_lastmodifieddate': '2022-12-14T17:33:09.711Z',
                             'hs_object_id': '5961164748',
                             'name': 'BFK ASSURANCES'},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2022, 12, 14, 17, 33, 9, 711000, tzinfo=tzutc())},
             {'archived': False,
              'archived_at': None,
              'associations': None,
              'created_at': datetime.datetime(2022, 8, 1, 12, 8, 19, 860000, tzinfo=tzutc()),
              'id': '5961164752',
              'properties': {'createdate': '2022-08-01T12:08:19.860Z',
                             'domain': None,
                             'hs_lastmodifieddate': '2022-12-14T17:33:14.086Z',
                             'hs_object_id': '5961164752',
                             'name': "DIA'VIE ASSURANCES CONSEILS"},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2022, 12, 14, 17, 33, 14, 86000, tzinfo=tzutc())},
             {'archived': False,
              'archived_at': None,
              'associations': None,
              'created_at': datetime.datetime(2022, 8, 1, 12, 8, 19, 864000, tzinfo=tzutc()),
              'id': '5961165247',
              'properties': {'createdate': '2022-08-01T12:08:19.864Z',
                             'domain': None,
                             'hs_lastmodifieddate': '2022-12-14T17:33:14.086Z',
                             'hs_object_id': '5961165247',
                             'name': 'JAMES JEAN YVES'},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2022, 12, 14, 17, 33, 14, 86000, tzinfo=tzutc())},
             {'archived': False,
              'archived_at': None,
              'associations': None,
              'created_at': datetime.datetime(2022, 8, 1, 12, 8, 19, 864000, tzinfo=tzutc()),
              'id': '5961165272',
              'properties': {'createdate': '2022-08-01T12:08:19.864Z',
                             'domain': None,
                             'hs_lastmodifieddate': '2022-12-14T17:33:13.532Z',
                             'hs_object_id': '5961165272',
                             'name': 'MEDLIFE PATRIMOINE'},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2022, 12, 14, 17, 33, 13, 532000, tzinfo=tzutc())},
             {'archived': False,
              'archived_at': None,
              'associations': None,
              'created_at': datetime.datetime(2022, 8, 1, 12, 8, 19, 862000, tzinfo=tzutc()),
              'id': '5961166527',
              'properties': {'createdate': '2022-08-01T12:08:19.862Z',
                             'domain': '2l-courtage.fr',
                             'hs_lastmodifieddate': '2022-12-14T17:33:06.725Z',
                             'hs_object_id': '5961166527',
                             'name': '2L COURTAGE'},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2022, 12, 14, 17, 33, 6, 725000, tzinfo=tzutc())},
             {'archived': False,
              'archived_at': None,
              'associations': None,
              'created_at': datetime.datetime(2022, 8, 1, 12, 8, 19, 862000, tzinfo=tzutc()),
              'id': '5961166528',
              'properties': {'createdate': '2022-08-01T12:08:19.862Z',
                             'domain': 'z-assurances.fr',
                             'hs_lastmodifieddate': '2022-12-14T17:33:06.725Z',
                             'hs_object_id': '5961166528',
                             'name': 'ZASSUR INVEST'},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2022, 12, 14, 17, 33, 6, 725000, tzinfo=tzutc())},
             {'archived': False,
              'archived_at': None,
              'associations': None,
              'created_at': datetime.datetime(2022, 8, 1, 12, 8, 19, 864000, tzinfo=tzutc()),
              'id': '5961166536',
              'properties': {'createdate': '2022-08-01T12:08:19.864Z',
                             'domain': None,
                             'hs_lastmodifieddate': '2022-12-14T17:33:10.737Z',
                             'hs_object_id': '5961166536',
                             'name': 'IRASSURANCES'},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2022, 12, 14, 17, 33, 10, 737000, tzinfo=tzutc())},
             {'archived': False,
              'archived_at': None,
              'associations': None,
              'created_at': datetime.datetime(2022, 8, 1, 12, 8, 19, 864000, tzinfo=tzutc()),
              'id': '5961167045',
              'properties': {'createdate': '2022-08-01T12:08:19.864Z',
                             'domain': None,
                             'hs_lastmodifieddate': '2022-12-14T17:33:12.855Z',
                             'hs_object_id': '5961167045',
                             'name': 'KREMER MARTINE'},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2022, 12, 14, 17, 33, 12, 855000, tzinfo=tzutc())},
             {'archived': False,
              'archived_at': None,
              'associations': None,
              'created_at': datetime.datetime(2022, 8, 1, 12, 8, 19, 861000, tzinfo=tzutc()),
              'id': '5961167047',
              'properties': {'createdate': '2022-08-01T12:08:19.861Z',
                             'domain': None,
                             'hs_lastmodifieddate': '2022-12-14T17:33:13.529Z',
                             'hs_object_id': '5961167047',
                             'name': 'MATH PREVARIS'},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2022, 12, 14, 17, 33, 13, 529000, tzinfo=tzutc())},
             {'archived': False,
              'archived_at': None,
              'associations': None,
              'created_at': datetime.datetime(2022, 8, 1, 12, 8, 19, 863000, tzinfo=tzutc()),
              'id': '5961167321',
              'properties': {'createdate': '2022-08-01T12:08:19.863Z',
                             'domain': 'cabinet-defigueiredo.fr',
                             'hs_lastmodifieddate': '2022-12-14T17:33:09.709Z',
                             'hs_object_id': '5961167321',
                             'name': 'CABINET DE FIGUEIREDO'},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2022, 12, 14, 17, 33, 9, 709000, tzinfo=tzutc())},
             {'archived': False,
              'archived_at': None,
              'associations': None,
              'created_at': datetime.datetime(2022, 8, 1, 12, 8, 19, 864000, tzinfo=tzutc()),
              'id': '5961167322',
              'properties': {'createdate': '2022-08-01T12:08:19.864Z',
                             'domain': None,
                             'hs_lastmodifieddate': '2022-12-14T17:33:12.856Z',
                             'hs_object_id': '5961167322',
                             'name': 'SIMON YVES'},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2022, 12, 14, 17, 33, 12, 856000, tzinfo=tzutc())},
             {'archived': False,
              'archived_at': None,
              'associations': None,
              'created_at': datetime.datetime(2022, 8, 1, 12, 32, 51, 350000, tzinfo=tzutc()),
              'id': '5961206724',
              'properties': {'createdate': '2022-08-01T12:32:51.350Z',
                             'domain': 'colibree.sitew.fr',
                             'hs_lastmodifieddate': '2022-12-14T17:33:08.152Z',
                             'hs_object_id': '5961206724',
                             'name': 'Association ColibrEE'},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2022, 12, 14, 17, 33, 8, 152000, tzinfo=tzutc())},
             {'archived': False,
              'archived_at': None,
              'associations': None,
              'created_at': datetime.datetime(2022, 8, 1, 12, 32, 51, 353000, tzinfo=tzutc()),
              'id': '5961206730',
              'properties': {'createdate': '2022-08-01T12:32:51.353Z',
                             'domain': 'jenniferlaurent.fr',
                             'hs_lastmodifieddate': '2022-12-14T17:33:06.216Z',
                             'hs_object_id': '5961206730',
                             'name': 'Jennifer Laurent'},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2022, 12, 14, 17, 33, 6, 216000, tzinfo=tzutc())},
             {'archived': False,
              'archived_at': None,
              'associations': None,
              'created_at': datetime.datetime(2022, 8, 1, 12, 32, 51, 348000, tzinfo=tzutc()),
              'id': '5961206731',
              'properties': {'createdate': '2022-08-01T12:32:51.348Z',
                             'domain': 'cedrepatrimoine.fr',
                             'hs_lastmodifieddate': '2023-02-01T15:18:20.985Z',
                             'hs_object_id': '5961206731',
                             'name': 'C�dre Patrimoine'},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2023, 2, 1, 15, 18, 20, 985000, tzinfo=tzutc())},
             {'archived': False,
              'archived_at': None,
              'associations': None,
              'created_at': datetime.datetime(2022, 8, 1, 12, 32, 51, 353000, tzinfo=tzutc()),
              'id': '5961206744',
              'properties': {'createdate': '2022-08-01T12:32:51.353Z',
                             'domain': 'fincab.fr',
                             'hs_lastmodifieddate': '2022-12-14T17:33:08.612Z',
                             'hs_object_id': '5961206744',
                             'name': 'FINCAB'},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2022, 12, 14, 17, 33, 8, 612000, tzinfo=tzutc())},
             {'archived': False,
              'archived_at': None,
              'associations': None,
              'created_at': datetime.datetime(2022, 8, 1, 12, 32, 51, 359000, tzinfo=tzutc()),
              'id': '5961206759',
              'properties': {'createdate': '2022-08-01T12:32:51.359Z',
                             'domain': 'aveniretdeveloppement.fr',
                             'hs_lastmodifieddate': '2022-12-14T17:33:06.716Z',
                             'hs_object_id': '5961206759',
                             'name': 'Avenir et Développement '},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2022, 12, 14, 17, 33, 6, 716000, tzinfo=tzutc())},
             {'archived': False,
              'archived_at': None,
              'associations': None,
              'created_at': datetime.datetime(2022, 8, 1, 12, 32, 51, 359000, tzinfo=tzutc()),
              'id': '5961206765',
              'properties': {'createdate': '2022-08-01T12:32:51.359Z',
                             'domain': 'bramham-gardens.com',
                             'hs_lastmodifieddate': '2022-12-14T17:33:12.848Z',
                             'hs_object_id': '5961206765',
                             'name': 'Bramham Gardens'},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2022, 12, 14, 17, 33, 12, 848000, tzinfo=tzutc())},
             {'archived': False,
              'archived_at': None,
              'associations': None,
              'created_at': datetime.datetime(2022, 8, 1, 12, 32, 51, 359000, tzinfo=tzutc()),
              'id': '5961206770',
              'properties': {'createdate': '2022-08-01T12:32:51.359Z',
                             'domain': 'invenit-conseil.com',
                             'hs_lastmodifieddate': '2022-12-14T17:33:08.612Z',
                             'hs_object_id': '5961206770',
                             'name': 'Invenit Conseil'},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2022, 12, 14, 17, 33, 8, 612000, tzinfo=tzutc())},
             {'archived': False,
              'archived_at': None,
              'associations': None,
              'created_at': datetime.datetime(2022, 8, 1, 12, 32, 51, 360000, tzinfo=tzutc()),
              'id': '5961206771',
              'properties': {'createdate': '2022-08-01T12:32:51.360Z',
                             'domain': 'cryptos-pilot.com',
                             'hs_lastmodifieddate': '2022-12-14T17:33:13.771Z',
                             'hs_object_id': '5961206771',
                             'name': 'Cryptos Pilot'},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2022, 12, 14, 17, 33, 13, 771000, tzinfo=tzutc())},
             {'archived': False,
              'archived_at': None,
              'associations': None,
              'created_at': datetime.datetime(2022, 8, 1, 12, 32, 51, 358000, tzinfo=tzutc()),
              'id': '5961206773',
              'properties': {'createdate': '2022-08-01T12:32:51.358Z',
                             'domain': 'geopatrimoine.com',
                             'hs_lastmodifieddate': '2022-12-14T17:33:06.716Z',
                             'hs_object_id': '5961206773',
                             'name': 'geo patrimoine'},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2022, 12, 14, 17, 33, 6, 716000, tzinfo=tzutc())}]}

In [11]:
from hubspot.crm.companies import PublicObjectSearchRequest, ApiException

client = hubspot.Client.create(access_token=apikey)

public_object_search_request = PublicObjectSearchRequest(filter_groups=[{"filters":[{"value":6166442171,"propertyName":"hs_object_id","operator":"EQ"}]}], sorts=["string"], query="string", properties=["blacklist","name"],limit=20,after=0)
try:
    api_response = client.crm.companies.search_api.do_search(public_object_search_request=public_object_search_request)
    pprint(api_response)
except ApiException as e:
    print("Exception when calling search_api->do_search: %s\n" % e)

{'paging': None,
 'results': [{'archived': False,
              'archived_at': None,
              'created_at': datetime.datetime(2022, 9, 5, 14, 29, 57, 241000, tzinfo=tzutc()),
              'id': '6166442171',
              'properties': {'blacklist': None,
                             'createdate': '2022-09-05T14:29:57.241Z',
                             'hs_lastmodifieddate': '2023-02-28T13:45:49.376Z',
                             'hs_object_id': '6166442171',
                             'name': 'Ivana String Quartet'},
              'properties_with_history': None,
              'updated_at': datetime.datetime(2023, 2, 28, 13, 45, 49, 376000, tzinfo=tzutc())}],
 'total': 1}

In [12]:
6622773481

6622773481

In [13]:
import requests

url = "https://api.hubapi.com/crm/v3/objects/companies/search"
headers={
    'Content-type':'application/json', 
    'authorization': 'Bearer %s' %apikey

}
body = {
    "filterGroups": [
    {
        "filters": [
        {
            "value": "true",
            "propertyName": "blacklist",
            "operator": "NEQ"
        },
        {
            "value": "Dead",
            "propertyName": "hs_lead_status",
            "operator": "EQ"
        },
        ],

    }
    ],

    "limit": 2,
    "after": 4
}
response = requests.request("POST", url,json=body,headers=headers)


print("total cpnm = "+str(response.json()['total']))
print((response.json()))

total cpnm = 20905
{'total': 20905, 'results': [{'id': '5961468357', 'properties': {'createdate': '2022-08-01T12:08:19.861Z', 'domain': None, 'hs_lastmodifieddate': '2022-12-14T17:33:13.773Z', 'hs_object_id': '5961468357', 'name': 'RISE ASSURANCE'}, 'createdAt': '2022-08-01T12:08:19.861Z', 'updatedAt': '2022-12-14T17:33:13.773Z', 'archived': False}, {'id': '5961491184', 'properties': {'createdate': '2022-08-01T12:08:19.862Z', 'domain': None, 'hs_lastmodifieddate': '2022-12-14T17:33:13.534Z', 'hs_object_id': '5961491184', 'name': 'SD CONSEIL'}, 'createdAt': '2022-08-01T12:08:19.862Z', 'updatedAt': '2022-12-14T17:33:13.534Z', 'archived': False}], 'paging': {'next': {'after': '6'}}}

In [14]:


def myBacklList(apikey):
    myrep = hs.getBacklList(apikey)
    print("total cpnm = "+str(myrep['total']))
    blackList = []
    try:
        while myrep.get('paging'):
            print("after = "+str(myrep['paging']['next']['after']))
            after = myrep['paging']['next']['after']
            for i in myrep['results']:
                blackList.append(i) #AGERER ICI
            myrep = hs.getBacklList(apikey,after)
        else:
            for i in myrep['results']:
                blackList.append(i)
    except Exception as e:
        print("end of list ",e)
    return blackList

In [15]:
myBacklList(apikey)

total cpnm = 1

[{'id': '7030222831',
  'properties': {'createdate': '2023-02-14T17:52:57.528Z',
   'domain': None,
   'hs_lastmodifieddate': '2023-02-14T17:55:52.837Z',
   'hs_object_id': '7030222831',
   'name': 'Entreprise Test BlackList'},
  'createdAt': '2023-02-14T17:52:57.528Z',
  'updatedAt': '2023-02-14T17:55:52.837Z',
  'archived': False}]

In [20]:
import re
import unidecode


def removeBlackList(df,apikey):
    blackList = myBacklList(apikey)
    df['name_normalized'] = df['Nom'].apply(lambda x: unidecode.unidecode(re.sub(r'[^\w\s_]', '', x.lower()).replace(' ', '').replace('_','')))
    print(df['name_normalized'])
    # Créer une liste contenant les noms normalisés de la blacklist
    blacklist_names = [unidecode.unidecode(re.sub(r'[^\w\s_]', '', item['properties']['name'].lower()).replace(' ', '').replace('_','')) for item in blackList]

    print(blacklist_names)
    # Sélectionner les lignes du dataframe qui ont une valeur dans la colonne "name_normalized" qui est dans la liste de la blacklist
    # df_filtered = df[~df['name_normalized'].isin(blacklist_names)]
    
    # Sélectionner les lignes du DataFrame qui ont une valeur dans la colonne "name_normalized"
    # qui contient une chaîne de caractères de la liste de la blacklist
    df_filtered = df[df['name_normalized'].str.contains('|'.join(blacklist_names))]
    
    # Supprimer la colonne "name_normalized" du dataframe final
    df = df.drop(df_filtered.index)

    return df

In [21]:
import netoyage_manageo.netoyage_mng as nm
cmp,ct = nm.test()
cmp.rename(columns={'nom company':'Nom'},inplace=True)
cmp

                 nom company Type principal Site internet (url racine)  \
0      Nom de l'entreprise 1    Secteur A 1       https://facebook.com
1      Nom de l'entreprise 2    Secteur A 2       https://facebook.com
2      Nom de l'entreprise 3    Secteur A 3       https://facebook.com
3  Entreprise Test BlackList    Secteur A 3       https://facebook.com

    Téléphone
0  0695342229
1  0695342229
2  0695342229
3         999

,Nom,Type principal,Site internet (url racine),Téléphone
0,Nom de l'entreprise 1,Secteur A 1,https://facebook.com,0695342229
1,Nom de l'entreprise 2,Secteur A 2,https://facebook.com,0695342229
2,Nom de l'entreprise 3,Secteur A 3,https://facebook.com,0695342229
3,Entreprise Test BlackList,Secteur A 3,https://facebook.com,999

In [24]:
cmp['Nom'][3] = "Ent``réprise-Test_blackList REGION SUD OUEST"
cmp

,Nom,Type principal,Site internet (url racine),Téléphone,name_normalized
0,Nom de l'entreprise 1,Secteur A 1,https://facebook.com,0695342229,nomdelentreprise1
1,Nom de l'entreprise 2,Secteur A 2,https://facebook.com,0695342229,nomdelentreprise2
2,Nom de l'entreprise 3,Secteur A 3,https://facebook.com,0695342229,nomdelentreprise3
3,Ent``réprise-Test_blackList REGION SUD OUEST,Secteur A 3,https://facebook.com,999,entreprisetestblacklist

In [25]:
removeBlackList(cmp,apikey)

total cpnm = 1
0                        nomdelentreprise1
1                        nomdelentreprise2
2                        nomdelentreprise3
3    entreprisetestblacklistregionsudouest
Name: name_normalized, dtype: object
['entreprisetestblacklist']

,Nom,Type principal,Site internet (url racine),Téléphone,name_normalized
0,Nom de l'entreprise 1,Secteur A 1,https://facebook.com,0695342229,nomdelentreprise1
1,Nom de l'entreprise 2,Secteur A 2,https://facebook.com,0695342229,nomdelentreprise2
2,Nom de l'entreprise 3,Secteur A 3,https://facebook.com,0695342229,nomdelentreprise3

In [35]:
import pandas as pd
def netoyage_email(input):
    mail_ban = ['prenom.nom@domaine.com','mail@mail.com']

      #Suppression des doublons
    input["Email"] = input["Email"].replace(" nan",'')
    input["Email"] = input["Email"].replace("nan",'')
    input["Email"] = input["Email"].fillna("")
    #Unique EMail
    input = input.assign(Unique_Email="")
    input["Unique_Email"] = input.apply(lambda x: x["Email"].split(" ")[0],axis = 1)
    
    return input

In [39]:
manageoDF = pd.read_csv("company.csv",sep=";")
manageoDF = pd.DataFrame(manageoDF,columns=['Siret','Raison sociale', 'Adresse normée ligne 4', 'Ville', 'Code postal', 'Libellé activité','Code activité', 'Date de création',
                                            'Tranche Effectif INSEE','Téléphone', 'Email', "Chiffre d'affaires" , 'Nom dirigeant principal', 'Prénom dirigeant principal'])
manageoDF

,Siret,Raison sociale,Adresse normée ligne 4,Ville,Code postal,Libellé activité,Code activité,Date de création,Tranche Effectif INSEE,Téléphone,Email,Chiffre d'affaires,Nom dirigeant principal,Prénom dirigeant principal
0,4725056800020,SOCIETE DE PARTICIPATION ET D'EXPLOITATION HOT...,19 RUE COPERNIC,PARIS 16,75116,Hôtels et hébergement similaire,5510Z,01/1974,10 à 19,145531491.0,contact@victorhugohotel.com,1080941,Blanc,Jacques
1,6080209700067,ETABLISSEMENTS TIANO,6 RUE DU GENERAL DELESTRAINT,PARIS 16,75016,"Intermédiaires du commerce en machines, équipe...",4614Z,01/1960,1 ou 2,NaN,NaN,619500,TIANO,ALFRED JACQUES
2,6080321000032,BENEX INTERNATIONAL,15 RUE DU DIX NEUF JANVIER,GARCHES,92380,Intermédiaires du commerce en bois et matériau...,4613Z,02/1984,1 ou 2,147952695.0,NaN,766565,BARICHELLA GILBERT,NaN
3,6520036200062,JEAN-CHARLES BROSSEAU SAS,129 AV DAUMESNIL,PARIS 12,75012,Fabrication de parfums et de produits pour la ...,2042Z,01/1964,1 ou 2,153338200.0,NaN,548675,BROSSEAU,Benoit
4,30006868100042,PRECISION MECANIQUE DE COUBRON,39 RUE AMPERE,GRETZ-ARMAINVILLIERS,77220,Mécanique industrielle,2562B,01/1974,3 à 5,164255087.0,contact@pmc-decoupage.fr,719449,HUMBERT,Sébastien David
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29797,99811550500013,SOCIETE MATIGNON SAINT-HONORE,34 AV MATIGNON,PARIS 8,75008,Commerce de détail de biens d'occasion en magasin,4779Z,01/1976,1 ou 2,NaN,NaN,588500,Malfet,Fabrice
29798,99817510300014,SOCIETE HOTELIERE PARIS-OUEST,17 RUE JEAN BAPTISTE DUMAS,PARIS 17,75017,Hôtels et hébergement similaire,5510Z,01/1976,10 à 19,145724451.0,reception@hotelmagellan.com,589484,PROGINOV CONSEIL (SARL),NaN
29799,99841701800038,ENTREPRISE D ETANCHEITE NABAIS,19 RUE GAMBETTA,STAINS,93240,Travaux d'étanchéification,4399A,01/1976,10 à 19,148265706.0,NaN,1127578,DE BASTOS,Antonio
29800,99862092600043,SARL DOMEAU CONCEPT,90 GRANDE RUE,SEVRES,92310,Fabrication de serrures et de ferrures,2572Z,01/1900,3 à 5,146266030.0,NaN,868987,WINZELBERG,Olivier
29801,99865011300041,MONTAGE CABLAGE ELECTRONIQUE DIFFUSION,17 RUE LEVACHER CINTRAT,MARCOUSSIS,91460,Fabrication d'équipements de communication,2630Z,01/1900,3 à 5,169015447.0,NaN,698930,LOUIS,FREDERIC JEAN PIERRE HENRI

In [38]:
manageoDF = netoyage_email(manageoDF)
manageoDF

,Siren,Siret,Raison sociale,Nature établissement,Adresse normée ligne 1,Adresse normée ligne 2,Adresse normée ligne 3,Adresse normée ligne 4,Adresse normée ligne 5,Adresse normée ligne 6,...,Mot-clé 10,Capital social,Entreprise exportatrice,CA réalisé à l'export,Part du CA réalisé à l'export,Téléphone,Fax,Email,Chiffre d'affaires,Unique_Email
0,47250568,4725056800020,SOCIETE DE PARTICIPATION ET D'EXPLOITATION HOT...,siège,SOCIETE DE PARTICIPATION ET D'EXPLOITATION HOT...,HOTEL VICTOR HUGO,NaN,19 RUE COPERNIC,NaN,75116 PARIS 16,...,monuments,800000.0,NON,NaN,NaN,145531491.0,NaN,contact@victorhugohotel.com,1080941,contact@victorhugohotel.com
1,60802097,6080209700067,ETABLISSEMENTS TIANO,siège,ETABLISSEMENTS TIANO,NaN,6-8,6 RUE DU GENERAL DELESTRAINT,NaN,75016 PARIS 16,...,NaN,95750.0,NON,NaN,NaN,NaN,NaN,,619500,
2,60803210,6080321000032,BENEX INTERNATIONAL,siège,BENEX INTERNATIONAL,NaN,NaN,15 RUE DU DIX NEUF JANVIER,NaN,92380 GARCHES,...,NaN,81200.0,OUI,765745.0,99.893 %,147952695.0,NaN,,766565,
3,65200362,6520036200062,JEAN-CHARLES BROSSEAU SAS,siège,JEAN-CHARLES BROSSEAU SAS,OMBRE ROSE,NaN,129 AV DAUMESNIL,NaN,75012 PARIS 12,...,NaN,39000.0,OUI,503013.0,91.678 %,153338200.0,NaN,,548675,
4,300068681,30006868100042,PRECISION MECANIQUE DE COUBRON,siège,PRECISION MECANIQUE DE COUBRON,NaN,ZONE INDUSTRIELLE AMPERE,39 RUE AMPERE,NaN,77220 GRETZ-ARMAINVILLIERS,...,NaN,105000.0,NON,NaN,NaN,164255087.0,NaN,contact@pmc-decoupage.fr,719449,contact@pmc-decoupage.fr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29797,998115505,99811550500013,SOCIETE MATIGNON SAINT-HONORE,siège,SOCIETE MATIGNON SAINT-HONORE,NaN,NaN,34 AV MATIGNON,NaN,75008 PARIS 8,...,NaN,20000.0,NON,NaN,NaN,NaN,NaN,,588500,
29798,998175103,99817510300014,SOCIETE HOTELIERE PARIS-OUEST,siège,SOCIETE HOTELIERE PARIS-OUEST,HOTEL MAGELLAN,NaN,17 RUE JEAN BAPTISTE DUMAS,NaN,75017 PARIS 17,...,standard,903555.0,NON,NaN,NaN,145724451.0,NaN,reception@hotelmagellan.com,589484,reception@hotelmagellan.com
29799,998417018,99841701800038,ENTREPRISE D ETANCHEITE NABAIS,siège,ENTREPRISE D ETANCHEITE NABAIS,NaN,19-21,19 RUE GAMBETTA,NaN,93240 STAINS,...,NaN,22867.0,NON,NaN,NaN,148265706.0,NaN,,1127578,
29800,998620926,99862092600043,SARL DOMEAU CONCEPT,siège,SARL DOMEAU CONCEPT,NaN,NaN,90 GRANDE RUE,NaN,92310 SEVRES,...,coffret,7622.0,NON,NaN,NaN,146266030.0,NaN,,868987,
29801,998650113,99865011300041,MONTAGE CABLAGE ELECTRONIQUE DIFFUSION,siège,MONTAGE CABLAGE ELECTRONIQUE DIFFUSION,MCE DIFFUSION,PA DE LA FONTAINE DE JOUVENCE,17 RUE LEVACHER CINTRAT,NaN,91460 MARCOUSSIS,...,mess,7622.0,NON,NaN,NaN,169015447.0,NaN,,698930,

In [44]:
manageoDFC = pd.read_csv("contact.csv",sep=";")
manageoDFC = pd.DataFrame(manageoDFC,columns=['Civilité','Nom', 'Prénom', 'Fonction', 'Raison sociale', 'Téléphone','Email'])
manageoDFC

,Civilité,Nom,Prénom,Fonction,Raison sociale,Téléphone,Email
0,M.,QUENNESSON,Olivier,Dir. des Ressources Humaines,SOCIETE DE PARTICIPATION ET D'EXPLOITATION HOT...,145531491.0,contact@victorhugohotel.com
1,M.,QUENNESSON,Olivier,Dir Administratif et Financier,SOCIETE DE PARTICIPATION ET D'EXPLOITATION HOT...,145531491.0,contact@victorhugohotel.com
2,MLE,ARTIERES,Maguelone,Directeur Marketing,SOCIETE DE PARTICIPATION ET D'EXPLOITATION HOT...,145531491.0,contact@victorhugohotel.com
3,MLE,ARTIERES,Maguelone,Directeur Commercial,SOCIETE DE PARTICIPATION ET D'EXPLOITATION HOT...,145531491.0,contact@victorhugohotel.com
4,M.,Blanc,Jacques,Président,SOCIETE DE PARTICIPATION ET D'EXPLOITATION HOT...,145531491.0,contact@victorhugohotel.com
...,...,...,...,...,...,...,...
32411,MME,DEQUAIRE,Hélène,Dir. des Ressources Humaines,SOCIETE HOTELIERE PARIS-OUEST,145724451.0,reception@hotelmagellan.com
32412,M.,PROGINOV CONSEIL (SARL),NaN,Président,SOCIETE HOTELIERE PARIS-OUEST,145724451.0,reception@hotelmagellan.com
32413,M.,DE BASTOS,Antonio,Gérant,ENTREPRISE D ETANCHEITE NABAIS,148265706.0,NaN
32414,M.,WINZELBERG,Olivier,Gérant,SARL DOMEAU CONCEPT,146266030.0,NaN
32415,M.,LOUIS,FREDERIC JEAN PIERRE HENRI,Gérant,MONTAGE CABLAGE ELECTRONIQUE DIFFUSION,169015447.0,NaN

In [104]:
#import un csv avec pandas et le convertir en dataframe
import pandas as pd
df = pd.read_csv("Black-list-partenaires-OPS-.csv",delimiter="\t")
df = pd.DataFrame(df)
cols = df.columns.values[0].replace(" / ","/").replace("SECTEURS BLACKLISTES","SECTEURS-BLACKLISTES").split(' ')
realCols = []
for e in cols:
    if(e != ''):
        realCols.append(e)
realCols = ['BANQUE/ASSURANCE/FINANCES',
 'DISTRIBUTION',
 'TOURISME',
 'IMMOBILIER',
 'SANTÉ',
 'TRANSPORT',
 'SERVICES',
 'HIGH TECH',
 'SECTEURS-BLACKLISTES']

In [114]:
myDataFrame = pd.DataFrame(columns=realCols)
myDataFrame

Empty DataFrame
Columns: [BANQUE/ASSURANCE/FINANCES, DISTRIBUTION, TOURISME, IMMOBILIER, SANTÉ, TRANSPORT, SERVICES, HIGH TECH, SECTEURS-BLACKLISTES]
Index: []

In [116]:
from itertools import zip_longest

for i in range (0,df.shape[0]):
    values = df[df.columns.values[0]][i].split("  ")
    realvalues = []
    for e in values:
        if(e != ''):
            #condi première ligne ...
            if(i == 0 and e == " Bouygues Telecom FABRICANTS HORLOGERIE"):
                tmp = 'Bouygues Telecom'      
                tmp2 = 'FABRICANTS HORLOGERIE'
                realvalues.append(tmp)
                realvalues.append(tmp2)
            else:    
                realvalues.append(e.strip())
    row = dict(zip_longest(myDataFrame.columns, realvalues, fillvalue=None))
    myDataFrame.loc[i] = row

myDataFrame

,BANQUE/ASSURANCE/FINANCES,DISTRIBUTION,TOURISME,IMMOBILIER,SANTÉ,TRANSPORT,SERVICES,HIGH TECH,SECTEURS-BLACKLISTES
0,AFER,Ebay,Ponant,ALPINE LODGES,ABBVIE,Aiways,DHL,Bouygues Telecom,FABRICANTS HORLOGERIE
1,AGIPI,Leclerc,SNCF,ALTAREA COGEDIM,AGENCE DE LA BIOMEDECINE,BMW,Geodis,SFR,JOAILLIER
2,ALLIANZ,Cdiscount,Club Med,ATLAND IMMOBILIER,ALLERGAN FRANCE SAS,Groupe Stellantis Homiris,Orange,MARCHE DE L'ART,None
3,ALTAPROFITS,Amazon,Accor,BARNES IMMOBILIER,BAYER SA,Honda,Korian,Hp,CINEMA
4,AMERICAN EXPRESS,Carrefour,Air France,BATI PARIS PROMOTION,BRISTOL MYERS SQUIBB,Hopium,La Poste,Dell,INFO-MEDIA
...,...,...,...,...,...,...,...,...,...
80,UBS,None,None,None,None,None,None,None,None
81,VEOLIA,None,None,None,None,None,None,None,None
82,VISA,None,None,None,None,None,None,None,None
83,YOMONI,None,None,None,None,None,None,None,None
84,,None,None,None,None,None,None,None,None

In [117]:
myDataFrame = myDataFrame.drop(myDataFrame.columns[-1], axis=1)

In [120]:
# Créer un nouveau DataFrame vide
new_df = pd.DataFrame(columns=['company_name', 'category', 'blacklist'])

# Parcourir chaque ligne du DataFrame original
for idx, row in myDataFrame.iterrows():
    # Parcourir chaque colonne du DataFrame original
    for col_name in myDataFrame.columns:
        # Si la valeur de la colonne n'est pas nulle et n'est pas dans la colonne SECTEURS-BLACKLISTES
        if not pd.isnull(row[col_name]) and col_name != 'SECTEURS-BLACKLISTES':
            # Ajouter une nouvelle ligne au nouveau DataFrame avec les valeurs correspondantes
            new_row = {'company_name': row[col_name], 'category': col_name, 'blacklist': True}
            new_df = new_df.append(new_row, ignore_index=True)

print(new_df.head())

    company_name                   category blacklist
0           AFER  BANQUE/ASSURANCE/FINANCES      True
1           Ebay               DISTRIBUTION      True
2         Ponant                   TOURISME      True
3  ALPINE LODGES                 IMMOBILIER      True
4         ABBVIE                      SANTÉ      True

In [121]:
new_df

      company_name                   category blacklist
0             AFER  BANQUE/ASSURANCE/FINANCES      True
1             Ebay               DISTRIBUTION      True
2           Ponant                   TOURISME      True
3    ALPINE LODGES                 IMMOBILIER      True
4           ABBVIE                      SANTÉ      True
..             ...                        ...       ...
221            UBS  BANQUE/ASSURANCE/FINANCES      True
222         VEOLIA  BANQUE/ASSURANCE/FINANCES      True
223           VISA  BANQUE/ASSURANCE/FINANCES      True
224         YOMONI  BANQUE/ASSURANCE/FINANCES      True
225                 BANQUE/ASSURANCE/FINANCES      True

[226 rows x 3 columns]

In [122]:
new_df.to_csv('cleanBlackList.csv', index=False)

In [26]:
apikey

'pat-eu1-91242dbb-e9d6-4b77-852f-fdd31151e049'

In [123]:
import requests
import json

# Définir l'URL de base pour l'API d'Hubspot
url_base = 'https://api.hubapi.com'

# Définir l'URL pour récupérer les transactions sur le pipeline Sales
url_sales = url_base + '/deals/v1/deal/paged?hapikey=',apikey,'&includeAssociations=true&associations=company'

# Récupérer les transactions sur le pipeline Sales
response_sales = requests.get(url_sales)
deals_sales = json.loads(response_sales.text)['deals']

# Définir l'URL pour récupérer les transactions sur le pipeline Customer
url_customer = url_base + '/crm/v3/objects/deals?hapikey=YOUR_HUBSPOT_API_KEY&properties=name&properties=dealstage&properties=amount&properties=hubspot_owner_id&properties=createdate&properties=dealtype&limit=100'

# Récupérer les transactions sur le pipeline Customer
response_customer = requests.get(url_customer)
deals_customer = json.loads(response_customer.text)['results']

# Comparer les transactions en fonction de leur nom
transaction_names_sales = [deal['properties']['dealname']['value'] for deal in deals_sales]
transaction_names_customer = [deal['properties']['name'] for deal in deals_customer]

# Afficher les transactions manquantes sur le pipeline Customer
missing_transactions = set(transaction_names_sales) - set(transaction_names_customer)
print("Transactions manquantes sur le pipeline Customer:")
print(missing_transactions)

InvalidSchema: No connection adapters were found for "('https://api.hubapi.com/deals/v1/deal/paged?hapikey=', 'pat-eu1-91242dbb-e9d6-4b77-852f-fdd31151e049', '&includeAssociations=true&associations=company')"

In [126]:
import requests
import json

# Définir l'URL de base pour l'API d'Hubspot
url_base = 'https://api.hubapi.com'

# Définir la clé API Hubspot
api_key = 'pat-eu1-91242dbb-e9d6-4b77-852f-fdd31151e049'

# Définir l'URL pour récupérer les transactions sur le pipeline Sales
url_sales = f'{url_base}/deals/v1/deal/paged?hapikey={api_key}&includeAssociations=true&associations=company'

# Récupérer les transactions sur le pipeline Sales
response_sales = requests.get(url_sales)
print(json.loads(response_sales.text))
deals_sales = json.loads(response_sales.text)['deals']

{'status': 'error', 'message': "This hapikey doesn't exist.", 'correlationId': 'e88ae6e5-8bc1-423e-937b-b9747f0af480'}

KeyError: 'deals'